version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install build dependencies
          command: |
            apk add --no-cache \
              bash \
              make \
              git
      - run:
          name: Build Docker Images
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            LLVM_VERSION=8 BASE_IMAGE='alpine:3.10' make all
            LLVM_VERSION=10 BASE_IMAGE='alpine:edge' make all
            LLVM_VERSION=9 BASE_IMAGE='alpine:3.11' make all